name       : libkgapi
version    : 22.04.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.0/src/libkgapi-22.04.0.tar.xz : 3c0711cf6316823c30c126028c5ad9e56f16f3950f2b0e02466ee9a26d0c793f
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - kcalendarcore-devel
    - kconfig-devel
    - kcontacts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
