name       : libkgapi
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/libkgapi-17.12.1.tar.xz : d4569bd7c8f76c5e33fd16557ab9283f77a6ab87fe9fe870583472eda408f59c
license    : LGPL-2.1
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API.
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcalcore-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - kio-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
setup      : |
    %patch -p1 < $pkgfiles/Fix-token-page-URL.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
