name       : libkgapi
version    : 20.12.1
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.1/src/libkgapi-20.12.1.tar.xz : 0df9a24e68d50f67e171ff5c6404891956c7fe675351bda8f8ab2a84ffa2a833
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
