name       : libkgapi
version    : 18.12.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/libkgapi-18.12.0.tar.xz : 7712137b6792bdcf89c34b9a742d0272a99c7e2eac5a7197dc68d567dcb9e934
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcalcore-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kio-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
