name       : libkgapi
version    : 20.12.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/libkgapi-20.12.0.tar.xz : da3f183df9ae5efde8244a0558203a27d0905e94b6af8721e570ad9820c31009
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Designer)
    - extra-cmake-modules
    - kcalendarcore-devel
    - kcodecs-devel
    - kconfig-devel
    - kcontacts-devel
    - kcoreaddons-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kwallet-devel
    - libboost-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
