name       : libkgapi
version    : 21.08.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/libkgapi-21.08.0.tar.xz : 79b8834de9cebe68b8059042c775dc9446306919b63a31a082273fa0ca995e38
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - kcalendarcore-devel
    - kconfig-devel
    - kcontacts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
