name       : libkgapi
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/libkgapi-21.04.1.tar.xz : 1dd464db972d037fda66af2eb6445c0d72e5d148f3d7b6ddcaaa5a048f33bb33
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - kcalendarcore-devel
    - kconfig-devel
    - kcontacts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
