name       : libkgapi
version    : 21.08.2
release    : 55
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/libkgapi-21.08.2.tar.xz : 40e95815d7c84edc86748c1ea2dbcb1ca187448af2c9a76460f3e3b12352b68d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - kcalendarcore-devel
    - kconfig-devel
    - kcontacts-devel
    - kwallet-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
