name       : libkgapi
version    : 19.04.1
release    : 22
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.1/src/libkgapi-19.04.1.tar.xz : a9d499fe1f5371112ceb94b3b03f8e2b1a1faa4ee69722b4c1c9ba28e8f9052e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Libkgapi is a KDE-based library for accessing various Google services via their public API
description: |
    Libkgapi is a KDE-based library for accessing various Google services via their public API.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - kcalcore-devel
    - kcontacts-devel
    - kdesignerplugin-devel
    - ki18n-devel
    - kio-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
